/**
 * @copyright (c) 2003 - 2022, Goodix Co., Ltd. All rights reserved.
 *
 * @file    gh3x_demo_algo_memory.h
 *
 * @brief   gh3x algo memory set
 *
 * @version ref gh3x_demo_algo_memory.h
 *
 */
#ifndef _GH3X_DEMO_ALGO_MEMORY_H_
#define _GH3X_DEMO_ALGO_MEMORY_H_

#include "gh3x_demo_algo_call.h"
#include "gh3x_demo_algo_config.h"

#if (__GOODIX_ALGO_CALL_MODE__)

/* algorithm mem size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_PEAK_1CHNL       (16392)       /**< HB 1 chnl algorithm peak memory size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_PEAK_2CHNL       (16392)       /**< HB 2 chnl  algorithm peak memory size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_PEAK_3CHNL       (16392)       /**< HB 3 chnl  algorithm peak memory size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_PEAK_4CHNL       (16392)       /**< HB 4 chnl  algorithm peak memory size in byte */

#define GH3X_HR_ALGORITHM_MEMORY_RESIDENT_1CHNL   (6056)       /**< HB 1 chnl  algorithm desident memory size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_RESIDENT_2CHNL   (6056)       /**< HB 2 chnl  algorithm desident memory size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_RESIDENT_3CHNL   (6056)       /**< HB 3 chnl  algorithm desident memory size in byte */
#define GH3X_HR_ALGORITHM_MEMORY_RESIDENT_4CHNL   (6056)       /**< HB 4 chnl  algorithm desident memory size in byte */

#define GH3X_HR_ALGORITHM_MEMORY_REDUNDANCY       (1000)


#define GH3X_SPO2_ALGORITHM_MEMORY_PEAK_1CHNL     (7864)       /**< SPO2 1 chnl  algorithm peak memory size in byte */
#define GH3X_SPO2_ALGORITHM_MEMORY_PEAK_2CHNL     (7864)       /**< SPO2 2 chnl  algorithm peak memory size in byte */
#define GH3X_SPO2_ALGORITHM_MEMORY_PEAK_3CHNL     (7864)       /**< SPO2 3 chnl  algorithm peak memory size in byte */
#define GH3X_SPO2_ALGORITHM_MEMORY_PEAK_4CHNL     (7864)       /**< SPO2 4 chnl  algorithm peak memory size in byte */

#define GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_1CHNL (5020)        /**< SPO2 1 chnl  algorithm memory size in byte */
#define GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_2CHNL (5020)       /**< SPO2 2 chnl  algorithm memory size in byte */
#define GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_3CHNL (5020)       /**< SPO2 3 chnl  algorithm memory size in byte */
#define GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_4CHNL (5020)       /**< SPO2 4 chnl  algorithm memory size in byte */

#define GH3X_SPO2_ALGORITHM_MEMORY_REDUNDANCY     (1000)


#define GH3X_ECG_ALGORITHM_MEMORY_PEAK            (38360)       /**< ECG algorithm peak memory size in byte */
#define GH3X_ECG_ALGORITHM_MEMORY_RESIDENT        (37176)       /**< ECG algorithm resident memory size in byte */
#define GH3X_ECG_ALGORITHM_MEMORY_REDUNDANCY      (1000)

#define GH3X_HRV_ALGORITHM_MEMORY_PEAK            (3008)        /**< HRV algorithm peak memory size in byte */
#define GH3X_HRV_ALGORITHM_MEMORY_RESIDENT        (2844)        /**< HRV algorithm resident memory size in byte */
#define GH3X_HRV_ALGORITHM_MEMORY_REDUNDANCY      (300)

#define GH3X_SOFT_ADT_ALGORITHM_MEMORY_PEAK       (1128)          /**< SOFT ADT algorithm peak memory size in byte */
#define GH3X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT   (104)          /**< SOFT ADT algorithm resident memory size in byte */
#define GH3X_SOFT_ADT_ALGORITHM_MEMORY_REDUNDANCY (100)        /**< SOFT ADT algorithm redundancy memory size in byte */

#define GH3X_HSM_ALGORITHM_MEMORY_PEAK            (944)       /**< HSM algorithm memory peak size in byte */
#define GH3X_HSM_ALGORITHM_MEMORY_RESIDENT        (944)       /**< HSM algorithm memory resident size in byte */
#define GH3X_HSM_ALGORITHM_MEMORY_REDUNDANCY      (100)


#define GH3X_BT_ALGORITHM_MEMORY_PEAK             (1600)        /**< BT algorithm memory peak size in byte */
#define GH3X_BT_ALGORITHM_MEMORY_RESIDENT         (1500)        /**< BT algorithm memory resident size in byte */
#define GH3X_BT_ALGORITHM_MEMORY_REDUNDANCY       (200)


#define GH3X_RESP_ALGORITHM_MEMORY_PEAK           (5435)        /**< RESP algorithm memory peak size in byte */
#define GH3X_RESP_ALGORITHM_MEMORY_RESIDENT       (2363)        /**< RESP algorithm memory resident size in byte */
#define GH3X_RESP_ALGORITHM_MEMORY_REDUNDANCY     (500)


#define GH3X_AF_ALGORITHM_MEMORY_PEAK             (3262)        /**< AF algorithm memory peak size in byte */
#define GH3X_AF_ALGORITHM_MEMORY_RESIDENT         (1102)        /**< AF algorithm memory resident size in byte */
#define GH3X_AF_ALGORITHM_MEMORY_REDUNDANCY       (300)

#define GH3X_BP_ALGORITHM_MEMORY_PEAK             (0)  /**< FPBP algorithm memory peak size in byte */
#define GH3X_BP_ALGORITHM_MEMORY_RESIDENT         (0)  /**< FPBP algorithm memory resident size in byte */
#define GH3X_BP_ALGORITHM_MEMORY_REDUNDANCY       (0)


/* algorithm mem config */
#if (__GOODIX_ALGO_CALL_MODE__)

#if (__USE_GOODIX_HR_ALGORITHM__)
#if __HR_ALGORITHM_SUPPORT_CHNL_NUM__ <= 1
#define   GH3X_ALGORITHM_HR_MEMORY_PEAK      GH3X_HR_ALGORITHM_MEMORY_PEAK_1CHNL
#define   GH3X_ALGORITHM_HR_MEMORY_RESIDENT  GH3X_HR_ALGORITHM_MEMORY_RESIDENT_1CHNL 
#elif __HR_ALGORITHM_SUPPORT_CHNL_NUM__ == 2
#define   GH3X_ALGORITHM_HR_MEMORY_PEAK   GH3X_HR_ALGORITHM_MEMORY_PEAK_2CHNL
#define   GH3X_ALGORITHM_HR_MEMORY_RESIDENT  GH3X_HR_ALGORITHM_MEMORY_RESIDENT_2CHNL 
#elif __HR_ALGORITHM_SUPPORT_CHNL_NUM__ == 3
#define   GH3X_ALGORITHM_HR_MEMORY_PEAK   GH3X_HR_ALGORITHM_MEMORY_PEAK_3CHNL
#define   GH3X_ALGORITHM_HR_MEMORY_RESIDENT  GH3X_HR_ALGORITHM_MEMORY_RESIDENT_3CHNL 
#elif __HR_ALGORITHM_SUPPORT_CHNL_NUM__ >= 4
#define   GH3X_ALGORITHM_HR_MEMORY_PEAK   GH3X_HR_ALGORITHM_MEMORY_PEAK_4CHNL
#define   GH3X_ALGORITHM_HR_MEMORY_RESIDENT  GH3X_HR_ALGORITHM_MEMORY_RESIDENT_4CHNL 
#endif
#define GH3X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_ALGORITHM_HR_MEMORY_PEAK - GH3X_ALGORITHM_HR_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_HR_MEMORY_REDUNDANCY                 GH3X_HR_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_HR_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_HR_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_HSM_ALGORITHM__)
#define   GH3X_ALGORITHM_HSM_MEMORY_RESIDENT   (GH3X_HSM_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_HSM_ALGORITHM_MEMORY_PEAK - GH3X_HSM_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_HSM_MEMORY_REDUNDANCY                GH3X_HSM_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_HSM_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_HSM_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_SPO2_ALGORITHM__)
#if __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ <= 1
#define   GH3X_ALGORITHM_SPO2_MEMORY_PEAK      GH3X_SPO2_ALGORITHM_MEMORY_PEAK_1CHNL
#define   GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT  GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_1CHNL 
#elif __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ == 2
#define   GH3X_ALGORITHM_SPO2_MEMORY_PEAK   GH3X_SPO2_ALGORITHM_MEMORY_PEAK_2CHNL
#define   GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT  GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_2CHNL 
#elif __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ == 3
#define   GH3X_ALGORITHM_SPO2_MEMORY_PEAK   GH3X_SPO2_ALGORITHM_MEMORY_PEAK_3CHNL
#define   GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT  GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_3CHNL 
#elif __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__ >= 4
#define   GH3X_ALGORITHM_SPO2_MEMORY_PEAK   GH3X_SPO2_ALGORITHM_MEMORY_PEAK_4CHNL
#define   GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT  GH3X_SPO2_ALGORITHM_MEMORY_RESIDENT_4CHNL 
#endif
#define GH3X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_ALGORITHM_SPO2_MEMORY_PEAK - GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_SPO2_MEMORY_REDUNDANCY                 GH3X_SPO2_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_SPO2_MEMORY_REDUNDANCY                (0)

#endif

#if (__USE_GOODIX_ECG_ALGORITHM__)
#define   GH3X_ALGORITHM_ECG_MEMORY_RESIDENT   (GH3X_ECG_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_ECG_ALGORITHM_MEMORY_PEAK - GH3X_ECG_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_ECG_MEMORY_REDUNDANCY                GH3X_ECG_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_ECG_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_ECG_MEMORY_REDUNDANCY                (0)
#endif

#if (__USE_GOODIX_HRV_ALGORITHM__)
#define   GH3X_ALGORITHM_HRV_MEMORY_RESIDENT   (GH3X_HRV_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_HRV_ALGORITHM_MEMORY_PEAK - GH3X_HRV_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_HRV_MEMORY_REDUNDANCY                GH3X_HRV_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_HRV_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_HRV_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_BT_ALGORITHM__)
#define   GH3X_ALGORITHM_BT_MEMORY_RESIDENT   (GH3X_BT_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_BT_ALGORITHM_MEMORY_PEAK - GH3X_BT_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_BT_MEMORY_REDUNDANCY                GH3X_BT_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_BT_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_BT_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_RESP_ALGORITHM__)
#define   GH3X_ALGORITHM_RESP_MEMORY_RESIDENT   (GH3X_RESP_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_RESP_ALGORITHM_MEMORY_PEAK - GH3X_RESP_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_RESP_MEMORY_REDUNDANCY                GH3X_RESP_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_RESP_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_RESP_MEMORY_REDUNDANCY               (0)
#endif

#if (__USE_GOODIX_AF_ALGORITHM__)
#define   GH3X_ALGORITHM_AF_MEMORY_RESIDENT   (GH3X_AF_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_AF_ALGORITHM_MEMORY_PEAK - GH3X_AF_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_AF_MEMORY_REDUNDANCY                GH3X_AF_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_AF_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_AF_MEMORY_REDUNDANCY               (0)
#endif


#if (__USE_GOODIX_SOFT_ADT_ALGORITHM__)
#define   GH3X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT   (GH3X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_SOFT_ADT_ALGORITHM_MEMORY_PEAK - GH3X_SOFT_ADT_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY                GH3X_SOFT_ADT_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY                (0)
#endif

#if (__USE_GOODIX_BP_ALGORITHM__)
#define   GH3X_ALGORITHM_BP_MEMORY_RESIDENT   (GH3X_BP_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_BP_MEMORY_PEAK_WITHOUT_RESIDENT    (GH3X_BP_ALGORITHM_MEMORY_PEAK - GH3X_BP_ALGORITHM_MEMORY_RESIDENT)
#define GH3X_ALGORITHM_BP_MEMORY_REDUNDANCY                GH3X_BP_ALGORITHM_MEMORY_REDUNDANCY
#else
#define GH3X_ALGORITHM_BP_MEMORY_RESIDENT   (0)
#define GH3X_ALGORITHM_BP_MEMORY_PEAK_WITHOUT_RESIDENT    (0)
#define GH3X_ALGORITHM_BP_MEMORY_REDUNDANCY                (0)
#endif

#endif


#define MAX2(a0, a1)                                   (((a0) > (a1)) ? (a0) : (a1))
#define ADD2(a0, a1)                                   ((a0) + (a1))
#define MAX4(a0,a1,a2,a3)                              (MAX2(MAX2(a0, a1),MAX2(a2, a3)))
#define MAX5(a0,a1,a2,a3,a4)                           (MAX2(MAX4(a0,a1,a2,a3),a4))
#define MAX9(a0, a1, a2, a3, a4, a5 ,a6, a7, a8)   (MAX2(MAX5(a0,a1,a2,a3,a4),MAX4(a5,a6,a7,a8))))

#define GH3X_FUNCTION_SOFT_ADT  (GH3X_FUNCTION_SOFT_ADT_GREEN|GH3X_FUNCTION_SOFT_ADT_IR)

#define   GH3X_ALGORITHMS_MEMORY_RESIDENT_(x) (\
    ((0 != (x & GH3X_FUNCTION_HR)) * __USE_GOODIX_HR_ALGORITHM__ * GH3X_ALGORITHM_HR_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_SPO2)) * __USE_GOODIX_SPO2_ALGORITHM__ * GH3X_ALGORITHM_SPO2_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_ECG)) * __USE_GOODIX_ECG_ALGORITHM__ * GH3X_ALGORITHM_ECG_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_HRV)) * __USE_GOODIX_HRV_ALGORITHM__ * GH3X_ALGORITHM_HRV_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_HSM)) * __USE_GOODIX_HSM_ALGORITHM__ * GH3X_ALGORITHM_HSM_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_BT)) * __USE_GOODIX_BT_ALGORITHM__ * GH3X_ALGORITHM_BT_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_RESP)) * __USE_GOODIX_RESP_ALGORITHM__ * GH3X_ALGORITHM_RESP_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_AF)) * __USE_GOODIX_AF_ALGORITHM__ * GH3X_ALGORITHM_AF_MEMORY_RESIDENT) + \
    ((0 != (x & GH3X_FUNCTION_SOFT_ADT)) * __USE_GOODIX_SOFT_ADT_ALGORITHM__ * GH3X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT))

#define   GH3X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT_(x) (MAX9(\
    ADD2(((0 != (x & GH3X_FUNCTION_HR))* __USE_GOODIX_HR_ALGORITHM__ * GH3X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_HR))* __USE_GOODIX_HR_ALGORITHM__ * GH3X_ALGORITHM_HR_MEMORY_REDUNDANCY)),\
    ADD2(((0 != (x & GH3X_FUNCTION_SPO2))* __USE_GOODIX_SPO2_ALGORITHM__* GH3X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_SPO2))* __USE_GOODIX_SPO2_ALGORITHM__* GH3X_ALGORITHM_SPO2_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_ECG))* __USE_GOODIX_ECG_ALGORITHM__* GH3X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_ECG))* __USE_GOODIX_ECG_ALGORITHM__* GH3X_ALGORITHM_ECG_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_HRV))* __USE_GOODIX_HRV_ALGORITHM__* GH3X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_HRV))* __USE_GOODIX_HRV_ALGORITHM__* GH3X_ALGORITHM_HRV_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_HSM))* __USE_GOODIX_HSM_ALGORITHM__* GH3X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_HSM))* __USE_GOODIX_HSM_ALGORITHM__* GH3X_ALGORITHM_HSM_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_BT))* __USE_GOODIX_BT_ALGORITHM__* GH3X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_BT))* __USE_GOODIX_BT_ALGORITHM__* GH3X_ALGORITHM_BT_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_RESP))* __USE_GOODIX_RESP_ALGORITHM__* GH3X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_RESP))* __USE_GOODIX_RESP_ALGORITHM__* GH3X_ALGORITHM_RESP_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_AF))* __USE_GOODIX_AF_ALGORITHM__* GH3X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_AF))* __USE_GOODIX_AF_ALGORITHM__* GH3X_ALGORITHM_AF_MEMORY_REDUNDANCY)), \
    ADD2(((0 != (x & GH3X_FUNCTION_SOFT_ADT))* __USE_GOODIX_SOFT_ADT_ALGORITHM__ * GH3X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT),\
    ((0 != (x & GH3X_FUNCTION_SOFT_ADT))* __USE_GOODIX_SOFT_ADT_ALGORITHM__ * GH3X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY)))

#define GH3X_ALGORITHMS_MEMORY_(x)  (GH3X_ALGORITHMS_MEMORY_RESIDENT_(x) + GH3X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT_(x))

#define __GH3X_ALGORITHMS_MEMORY  (\
                                    MAX5(\
                                    GH3X_ALGORITHMS_MEMORY_(GH3X_ALGO_FUNCTION_GROUP_0),\
                                    GH3X_ALGORITHMS_MEMORY_(GH3X_ALGO_FUNCTION_GROUP_1),\
                                    GH3X_ALGORITHMS_MEMORY_(GH3X_ALGO_FUNCTION_GROUP_2),\
                                    GH3X_ALGORITHMS_MEMORY_(GH3X_ALGO_FUNCTION_GROUP_3),\
                                    GH3X_ALGORITHMS_MEMORY_(GH3X_ALGO_FUNCTION_GROUP_4)\
                                    )\
                                )
//final size
#define GH3X_ALGORITHMS_MEMORY_SIZE_FINAL  (((GU32)((__GH3X_ALGORITHMS_MEMORY + 3) / 4)) * 4)


/**
 * @fn     GS8 GH3X_AlgoMemConfig( GU32 unMemSize)
 *
 * @brief  Config algorithm memory.
 *
 * @attention   Mem can only be static,such as global array
 *
 * @param[in]  unMemSize       memory size(unit:byte)
 *
 * @return  error code
 * @retval  #GH3X_RET_OK                      return successfully
 * @retval  #GH3X_RET_RESOURCE_ERROR          return algorithm mem config error
 */
GS8 GH3X_AlgoMemConfig( GU32 unMemSize);

#endif

#endif /* _GH3X_DEMO_ALGO_CALL_H_ */

/********END OF FILE********* Copyright (c) 2003 - 2022, Goodix Co., Ltd. ********/
